plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true   # Allow .md in dir works


# include:
#   - CONTRIBUTING.md
#   - README.md
#   - LICENSE.md
#   - COPYING.md
#   - CODE_OF_CONDUCT.md
#   - CONTRIBUTING.md
#   - ISSUE_TEMPLATE.md
#   - PULL_REQUEST_TEMPLATE.md